version: '3'

services:
  spring-boot-eureka-client:
    image: spring-boot-eureka-client
    container_name: eurekaClient
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 8089
    ports:
      - 8089:8089
    volumes:
      - /data/spring-boot-app