-- MySQL Script generated by MySQL Workbench
-- Mon Oct  8 09:20:22 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bbf
-- -----------------------------------------------------
-- Model to manage the actual Barcelona Beer Festival.
DROP SCHEMA IF EXISTS `bbf` ;

-- -----------------------------------------------------
-- Schema bbf
--
-- Model to manage the actual Barcelona Beer Festival.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bbf` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `bbf` ;

-- -----------------------------------------------------
-- Table `bbf`.`BREWERY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bbf`.`BREWERY` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bbf`.`BREWERY` (
  `idBrewery` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(128) NOT NULL,
  `Location` VARCHAR(128) NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Foundation` VARCHAR(45) NULL,
  `CreationDate` TIMESTAMP NULL,
  `ModifyDate` TIMESTAMP NULL,
  PRIMARY KEY (`idBrewery`))
ENGINE = InnoDB;

SHOW WARNINGS;
USE `bbf`;

DELIMITER $$

USE `bbf`$$
DROP TRIGGER IF EXISTS `bbf`.`BREWERY_BEFORE_INSERT` $$
SHOW WARNINGS$$
USE `bbf`$$
CREATE DEFINER = CURRENT_USER TRIGGER `bbf`.`BREWERY_BEFORE_INSERT` BEFORE INSERT ON `BREWERY` FOR EACH ROW
BEGIN
	SET NEW.CreationDate = NOW();
END$$

SHOW WARNINGS$$

USE `bbf`$$
DROP TRIGGER IF EXISTS `bbf`.`BREWERY_BEFORE_UPDATE` $$
SHOW WARNINGS$$
USE `bbf`$$
CREATE DEFINER = CURRENT_USER TRIGGER `bbf`.`BREWERY_BEFORE_UPDATE` BEFORE UPDATE ON `BREWERY` FOR EACH ROW
BEGIN
	SET NEW.ModifyDate = NOW();
END$$

SHOW WARNINGS$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
